#!/usr/bin/env node
/**
 * Extract the `#region snippet:<name>` blocks from the reference sources into a
 * module the vault imports, so the Code note quotes real files rather than a
 * copy that quietly rots.
 *
 *   node tools/snippets.mjs           # regenerate
 *   node tools/snippets.mjs --check   # fail if the generated file is stale
 */

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = 'src/js/snippets.generated.js';

const SOURCES = [
  { key: 'stata', language: 'Stata', file: 'reference/stata/dynamic_panel.do', region: 'core' },
  { key: 'r', language: 'R', file: 'reference/r/dynamic_panel.R', region: 'core' },
  { key: 'javascript', language: 'JavaScript', file: 'src/js/sim/gmm.js', region: 'core' },
  { key: 'csharp', language: 'C#', file: 'reference/csharp/DynamicPanel/Estimators.cs', region: 'core' },
  { key: 'cpp', language: 'C++', file: 'reference/cpp/gmm.cpp', region: 'core' }
];

const START = (region) => new RegExp(`#region\\s+snippet:${region}\\b`);
const END = /#endregion\b/;

/** Pull one marked region out of a source file, dedented, comment markers dropped. */
export function extractRegion(source, region, where) {
  const lines = source.split('\n');
  const start = lines.findIndex((line) => START(region).test(line));
  if (start === -1) throw new Error(`${where}: no "#region snippet:${region}" marker`);

  const end = lines.findIndex((line, i) => i > start && END.test(line));
  if (end === -1) throw new Error(`${where}: "#region snippet:${region}" is never closed`);

  const body = lines.slice(start + 1, end);
  while (body.length && body[0].trim() === '') body.shift();
  while (body.length && body[body.length - 1].trim() === '') body.pop();
  if (!body.length) throw new Error(`${where}: region "${region}" is empty`);

  const indent = Math.min(...body
    .filter((line) => line.trim() !== '')
    .map((line) => line.match(/^[ \t]*/)[0].length));

  return body.map((line) => line.slice(indent)).join('\n');
}

async function build() {
  const entries = [];
  for (const source of SOURCES) {
    const text = await readFile(join(ROOT, source.file), 'utf8');
    entries.push({
      key: source.key,
      language: source.language,
      file: source.file,
      code: extractRegion(text, source.region, source.file)
    });
  }

  const body = entries.map(({ key, language, file, code }) => `  ${JSON.stringify(key)}: {
    language: ${JSON.stringify(language)},
    file: ${JSON.stringify(file)},
    code: ${JSON.stringify(code)}
  }`).join(',\n');

  return `/* GENERATED by tools/snippets.mjs — do not edit.
 * Regenerate with \`npm run snippets\` after changing a reference implementation.
 */

export const SNIPPETS = {
${body}
};
`;
}

async function main() {
  const check = process.argv.includes('--check');
  const generated = await build();
  const path = join(ROOT, OUTPUT);

  if (!check) {
    await writeFile(path, generated, 'utf8');
    console.log(`snippets: wrote ${OUTPUT} (${SOURCES.length} languages)`);
    return 0;
  }

  let current = null;
  try {
    current = await readFile(path, 'utf8');
  } catch {
    console.error(`snippets: ${OUTPUT} is missing — run \`npm run snippets\``);
    return 1;
  }

  if (current !== generated) {
    console.error(`snippets: ${OUTPUT} is stale — run \`npm run snippets\``);
    return 1;
  }

  console.log(`snippets: ${OUTPUT} is up to date`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = await main();
}
